# Generated by Django 5.1.5 on 2025-06-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PunteggiBlu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PunteggiGialli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PunteggiRossi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PunteggiVerdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField()),
            ],
        ),
    ]
