# Generated by Django 5.1.5 on 2025-06-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(blank=True, max_length=100)),
                ('squadra', models.CharField(blank=True, choices=[('Rossi', 'Rossi'), ('Blu', 'Blu'), ('Verdi', 'Verdi'), ('Gialli', 'Gialli')], max_length=6, null=True)),
                ('uscita_autonoma', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('animato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_app.animato')),
            ],
            options={
                'unique_together': {('animato', 'data')},
            },
        ),
    ]
