# Generated by Django 5.1.5 on 2025-07-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0002_animato_presenza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presenza',
        ),
    ]
