# Generated by Django 5.1.5 on 2025-07-02 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0003_delete_presenza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('entrata', models.BooleanField(default=False)),
                ('uscita', models.BooleanField(default=False)),
                ('animato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_app.animato')),
            ],
        ),
    ]
