# Generated by Django 5.1.5 on 2025-07-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0004_presenza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenza',
            name='data',
            field=models.DateField(),
        ),
    ]
