# Generated by Django 5.1.5 on 2025-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0005_alter_presenza_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='animato',
            name='anno_di_nascita',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
