# Generated by Django 5.1.5 on 2025-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0006_animato_anno_di_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animato',
            name='anno_di_nascita',
            field=models.IntegerField(blank=True, choices=[('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=4, null=True),
        ),
    ]
