# Generated by Django 5.1.5 on 2025-07-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0008_alter_animato_anno_di_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animato',
            name='anno_di_nascita',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
