# Generated by Django 5.1.5 on 2025-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0009_alter_animato_anno_di_nascita'),
    ]

    operations = [
        migrations.CreateModel(
            name='cucina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mansione', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Iscritto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
