# Generated by Django 5.1.5 on 2025-07-27 07:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0010_cucina_iscritto'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscritto',
            name='allergie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='cognome_figlio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='contatti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='cucina',
            field=models.ManyToManyField(to='b_app.cucina'),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='data_figlio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='fratelli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='luogo_nascita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='madre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='nome_figlio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='padre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='residenza',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='sito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='telefono1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IT'),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='telefono2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IT'),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='tutore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iscritto',
            name='uscita_autonoma',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
