# Generated by Django 5.1.5 on 2025-07-27 07:54

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0011_iscritto_allergie_iscritto_cognome_figlio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscritto',
            name='cognome_figlio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='data_figlio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='luogo_nascita',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='nome_figlio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='residenza',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='telefono1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IT'),
        ),
    ]
