# Generated by Django 5.1.5 on 2025-07-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0012_alter_iscritto_cognome_figlio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscritto',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
