# Generated by Django 5.1.5 on 2025-07-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0013_alter_iscritto_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='sino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risposta', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='iscritto',
            name='gita',
            field=models.ManyToManyField(to='b_app.sino'),
        ),
    ]
