# Generated by Django 5.1.5 on 2025-07-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0014_sino_iscritto_gita'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscritto',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documenti/'),
        ),
    ]
