# Generated by Django 5.1.5 on 2025-07-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0015_iscritto_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagamenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='iscritto',
            name='pagamenti',
            field=models.ManyToManyField(to='b_app.pagamenti'),
        ),
    ]
