# Generated by Django 5.1.5 on 2025-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0016_pagamenti_iscritto_pagamenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamenti',
            name='cash',
            field=models.CharField(max_length=20),
        ),
    ]
