# Generated by Django 5.1.5 on 2025-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0017_alter_pagamenti_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscritto',
            name='necessita',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
