# Generated by Django 5.1.5 on 2025-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0018_iscritto_necessita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animato',
            name='anno_di_nascita',
        ),
        migrations.AddField(
            model_name='animato',
            name='data_di_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animato',
            name='cognome',
            field=models.CharField(max_length=100),
        ),
    ]
