# Generated by Django 5.1.5 on 2025-07-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0019_remove_animato_anno_di_nascita_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animato',
            old_name='data_di_nascita',
            new_name='anno_di_nascita',
        ),
    ]
