# Generated by Django 5.1.5 on 2025-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0020_rename_data_di_nascita_animato_anno_di_nascita'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=500, null=True)),
                ('Documento', models.FileField(upload_to='documenti/')),
            ],
        ),
    ]
