# Generated by Django 5.1.5 on 2025-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0021_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Documento',
            field=models.FileField(blank=True, null=True, upload_to='documenti/'),
        ),
    ]
