# Generated by Django 5.1.5 on 2025-07-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0022_alter_file_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Documento',
            field=models.FileField(upload_to='documenti/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='Nome',
            field=models.CharField(max_length=500),
        ),
    ]
