# Generated by Django 5.1.5 on 2025-07-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0023_alter_file_documento_alter_file_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscritto',
            name='pagamenti',
            field=models.ManyToManyField(blank=True, null=True, to='b_app.pagamenti'),
        ),
    ]
