# Generated by Django 5.1.5 on 2025-07-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0024_alter_iscritto_pagamenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscritto',
            name='cucina',
            field=models.ManyToManyField(blank=True, null=True, to='b_app.cucina'),
        ),
    ]
