# Generated by Django 5.1.5 on 2025-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0025_alter_iscritto_cucina'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscritto',
            name='laboratori',
            field=models.BooleanField(default=False),
        ),
    ]
