# Generated by Django 5.1.5 on 2025-07-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0026_iscritto_laboratori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iscritto',
            name='cucina',
            field=models.ManyToManyField(blank=True, to='b_app.cucina'),
        ),
        migrations.AlterField(
            model_name='iscritto',
            name='pagamenti',
            field=models.ManyToManyField(blank=True, to='b_app.pagamenti'),
        ),
    ]
