# Generated by Django 5.1.5 on 2025-07-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0027_alter_iscritto_cucina_alter_iscritto_pagamenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscritto',
            name='squadra',
            field=models.CharField(blank=True, choices=[('Rossi', 'Rossi'), ('Blu', 'Blu'), ('Verdi', 'Verdi'), ('Gialli', 'Gialli')], max_length=10, null=True),
        ),
    ]
