# Generated by Django 5.1.5 on 2025-07-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0028_iscritto_squadra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenza',
            name='animato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_app.iscritto'),
        ),
        migrations.RemoveField(
            model_name='iscritto',
            name='gita',
        ),
        migrations.DeleteModel(
            name='Animato',
        ),
        migrations.AddField(
            model_name='iscritto',
            name='gita',
            field=models.BooleanField(default=False),
        ),
    ]
