# Generated by Django 5.1.5 on 2025-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_app', '0029_alter_presenza_animato_remove_iscritto_gita_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPerGenitori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=500)),
                ('Documento', models.FileField(upload_to='documenti/')),
            ],
        ),
    ]
